from __future__ import annotations

from typing import Any

import numpy as np

from spritespatial.sdf_volume import labels_present_in_parts


def build_phase5a_validation(
    mylar: dict[str, Any],
    back: dict[str, Any],
    seam: dict[str, Any],
    sdf: dict[str, Any],
    meshing: dict[str, Any],
    parts: list[dict[str, Any]],
    back_mode: str,
    source_coverage: dict[str, Any] | None = None,
    semantic_authority: dict[str, Any] | None = None,
    semantic_parts: dict[str, Any] | None = None,
) -> dict[str, Any]:
    source_coverage = source_coverage or {}
    semantic_authority = semantic_authority or {}
    semantic_parts = semantic_parts or {}
    mylar_report = mylar["report"]
    back_report = back["report"]
    seam_report = seam["report"]
    sdf_summary = sdf["summary"]
    semantic_depth_enabled = bool(sdf_summary.get("semantic_depth_profiles_enabled", False))
    directional_enabled = bool(sdf_summary.get("directional_morphology_enabled", False))
    surface_flow_enabled = bool(sdf_summary.get("surface_flow_enabled", False))
    rfd_enabled = bool(sdf_summary.get("rfd_enabled", False))
    semantic_authority_enabled = bool(semantic_authority.get("semantic_authority_enabled", False))
    semantic_parts_enabled = bool(semantic_parts.get("semantic_parts_enabled", False))
    mesh_report = meshing["report"]
    required_labels = labels_present_in_parts(parts)
    present_labels = list(sdf_summary.get("semantic_volume_labels", []))
    missing_labels = [label for label in required_labels if label not in present_labels]
    z_front = mylar["z_front"]
    z_back = back["z_back"]
    fail_conditions = {
        "silhouette_pin_fails": not mylar_report.get("silhouette_pin_confirmed", False),
        "front_back_seam_mismatch_exceeds_tolerance": seam_report.get("seam_discontinuity_max", 1.0) > 1e-6,
        "sdf_volume_empty": int(sdf_summary.get("occupied_voxels", 0)) <= 0,
        "critical_semantic_labels_disappear": bool(missing_labels),
        "hollow_gap_ratio_exceeds_threshold": float(sdf_summary.get("hollow_gap_ratio", 1.0)) > 0.20,
        "closed_volume_disconnected": not sdf_summary.get("closed_volume_connected", False),
        "z_front_contains_negative_values": bool(np.any(z_front < 0.0)),
        "z_back_contains_positive_values": bool(np.any(z_back > 0.0)),
        "semantic_volume_loses_labels_present_in_phase_1_4": bool(missing_labels),
        "surface_nets_input_not_loadable": not mesh_report.get("surface_nets_input_loadable", False),
        "inner_holes_detected_not_seamed": seam_report.get("inner_holes_detected", 0) != seam_report.get("inner_holes_seamed", 0),
        "mylar_isolated_spikes": mylar_report.get("isolated_spike_count", 0) > 0,
        "outline_full_depth_slab": mylar_report.get("outline_full_depth_slab", False),
        "missing_critical_back_regions": bool(back_report.get("missing_critical_back_regions", [])),
        "source_coverage_policy_failed": any(source_coverage.get("fail_conditions", {}).values()),
        "semantic_authority_failed": semantic_authority_enabled and not semantic_authority.get("passed", False),
        "semantic_parts_failed": semantic_parts_enabled and not semantic_parts.get("passed", False),
        "semantic_parts_geometry_not_canonical": semantic_parts_enabled
        and not semantic_parts.get("geometry_uses_canonical_parts", False),
        "semantic_depth_uniform_slab": semantic_depth_enabled and float(sdf_summary.get("uniform_slab_ratio", 1.0)) > 0.70,
        "semantic_depth_variance_missing": semantic_depth_enabled and float(sdf_summary.get("semantic_depth_variance", 0.0)) <= 0.0,
        "semantic_outline_shell_too_thick": semantic_depth_enabled and float(sdf_summary.get("outline_shell_ratio", 0.0)) > 1.0,
        "semantic_side_profile_unreadable": semantic_depth_enabled and float(sdf_summary.get("side_profile_readability_score", 0.0)) < 0.20,
        "directional_morphology_missing": directional_enabled and int(sdf_summary.get("directional_semantic_count", 0)) <= 0,
        "directional_morphology_unreadable": directional_enabled
        and float(sdf_summary.get("directional_readability_score", 0.0)) < 0.10,
        "hat_pointed_back_asymmetry_low": directional_enabled
        and bool(sdf_summary.get("hat_pointed_back_present", False))
        and float(sdf_summary.get("hat_asymmetry_ratio", 0.0)) <= 2.0,
        "surface_flow_missing_transitions": surface_flow_enabled and int(sdf_summary.get("semantic_transition_count", 0)) <= 0,
        "surface_flow_continuity_low": surface_flow_enabled and float(sdf_summary.get("surface_continuity_score", 0.0)) < 0.12,
        "surface_flow_anatomical_flow_low": surface_flow_enabled and float(sdf_summary.get("anatomical_flow_score", 0.0)) < 0.20,
        "surface_flow_fragmentation_high": surface_flow_enabled
        and float(sdf_summary.get("surface_fragmentation_score", 1.0)) > 0.85,
        "rfd_regions_missing": rfd_enabled and int(sdf_summary.get("rfd_region_count", 0)) <= 0,
        "rfd_centerline_quality_low": rfd_enabled and float(sdf_summary.get("centerline_quality_score", 0.0)) < 0.10,
        "rfd_field_continuity_low": rfd_enabled and float(sdf_summary.get("field_continuity_score", 0.0)) < 0.20,
        "rfd_silhouette_constraints_lost": rfd_enabled and float(sdf_summary.get("silhouette_constraint_preservation", 0.0)) < 0.95,
    }
    return {
        "mylar_depth_enabled": True,
        "closed_body_enabled": True,
        "back_mode": back_mode,
        "front_max_depth": float(z_front.max()) if z_front.size else 0.0,
        "back_max_depth": float(abs(z_back.min())) if z_back.size else 0.0,
        "silhouette_pin_confirmed": mylar_report.get("silhouette_pin_confirmed", False),
        "seam_ring_count": seam_report.get("seam_ring_count", 0),
        "seam_discontinuity_max": seam_report.get("seam_discontinuity_max", 0.0),
        "inner_holes_detected": seam_report.get("inner_holes_detected", 0),
        "inner_holes_seamed": seam_report.get("inner_holes_seamed", 0),
        "sdf_volume_shape": sdf_summary.get("shape", []),
        "sdf_source_shape": sdf_summary.get("source_shape", []),
        "sdf_resolution_scale": sdf_summary.get("sdf_resolution_scale", 1.0),
        "z_samples": sdf_summary.get("z_samples", 0),
        "adaptive_sdf_resolution_enabled": sdf_summary.get("adaptive_sdf_resolution_enabled", False),
        "resolution_profile": sdf_summary.get("resolution_profile", ""),
        "effective_voxel_budget_multiplier": sdf_summary.get("effective_voxel_budget_multiplier", 1.0),
        "adaptive_high_detail_region_count": sdf_summary.get("adaptive_high_detail_region_count", 0),
        "silhouette_band_high_res_enabled": sdf_summary.get("silhouette_band_high_res_enabled", False),
        "semantic_boundary_high_res_enabled": sdf_summary.get("semantic_boundary_high_res_enabled", False),
        "sdf_resolution_strategy": sdf_summary.get("sdf_resolution_strategy", "uniform"),
        "sdf_sign_consistency": sdf_summary.get("sdf_sign_consistency", False),
        "sdf_dtype": sdf_summary.get("sdf_dtype", ""),
        "semantic_dtype": sdf_summary.get("semantic_dtype", ""),
        "closed_volume_connected": sdf_summary.get("closed_volume_connected", False),
        "hollow_gap_ratio": sdf_summary.get("hollow_gap_ratio", 1.0),
        "semantic_volume_labels": present_labels,
        "required_semantic_volume_labels": required_labels,
        "missing_semantic_volume_labels": missing_labels,
        "surface_nets_input_loadable": mesh_report.get("surface_nets_input_loadable", False),
        "surface_nets_input_shape_valid": mesh_report.get("surface_nets_input_shape_valid", False),
        "surface_nets_ready": mesh_report.get("surface_nets_input_loadable", False)
        and mesh_report.get("surface_nets_input_shape_valid", False),
        "manifold_ready_estimate": sdf_summary.get("closed_volume_connected", False)
        and sdf_summary.get("sdf_sign_consistency", False),
        "front_back_sprite_deferred": back_report.get("front_back_sprite_deferred", False),
        "back_geometry_authority": back_report.get("back_geometry_authority", semantic_authority.get("back_geometry_authority", "")),
        "source_coverage": source_coverage,
        "build_warnings": list(source_coverage.get("warnings", []))
        + list(semantic_authority.get("warnings", []))
        + list(semantic_parts.get("warnings", [])),
        "semantic_authority_enabled": semantic_authority_enabled,
        "override_overlap_ratio": semantic_authority.get("override_overlap_ratio", 0.0),
        "hat_authority_passed": semantic_authority.get("hat_authority_passed", True),
        "hat_pixel_count": semantic_authority.get("hat_pixel_count", 0),
        "hat_component_count": semantic_authority.get("hat_component_count", 0),
        "hat_head_attachment_score": semantic_authority.get("hat_head_attachment_score", 0.0),
        "hat_torso_overlap_count": semantic_authority.get("hat_torso_overlap_count", 0),
        "hat_directional_morphology_allowed": semantic_authority.get("hat_directional_morphology_allowed", False),
        "directional_morphology_gated_labels": semantic_authority.get("directional_morphology_gated_labels", []),
        "front_back_semantic_correspondence_passed": semantic_authority.get(
            "front_back_semantic_correspondence_passed", True
        ),
        "semantic_parts_enabled": semantic_parts_enabled,
        "raw_region_count": semantic_parts.get("raw_region_count", 0),
        "canonical_part_count": semantic_parts.get("canonical_part_count", 0),
        "part_reduction_ratio": semantic_parts.get("part_reduction_ratio", 0.0),
        "tiny_orphans_absorbed": semantic_parts.get("tiny_orphans_absorbed", 0),
        "outline_debris_removed": semantic_parts.get("outline_debris_removed", 0),
        "geometry_uses_canonical_parts": semantic_parts.get("geometry_uses_canonical_parts", not semantic_parts_enabled),
        "canonical_required_parts_present": semantic_parts.get("canonical_required_parts_present", True),
        "semantic_part_warnings": list(semantic_parts.get("warnings", [])),
        "semantic_depth_profiles_enabled": semantic_depth_enabled,
        "semantic_depth_profile": sdf_summary.get("semantic_depth_profile", ""),
        "uniform_slab_ratio": sdf_summary.get("uniform_slab_ratio", 0.0),
        "semantic_depth_variance": sdf_summary.get("semantic_depth_variance", 0.0),
        "head_depth_ratio": sdf_summary.get("head_depth_ratio", 0.0),
        "torso_depth_ratio": sdf_summary.get("torso_depth_ratio", 0.0),
        "limb_depth_ratio": sdf_summary.get("limb_depth_ratio", 0.0),
        "outline_shell_ratio": sdf_summary.get("outline_shell_ratio", 0.0),
        "side_projection_entropy": sdf_summary.get("side_projection_entropy", 0.0),
        "side_profile_readability_score": sdf_summary.get("side_profile_readability_score", 0.0),
        "directional_morphology_enabled": directional_enabled,
        "morphology_profile": sdf_summary.get("morphology_profile", ""),
        "directional_semantic_count": sdf_summary.get("directional_semantic_count", 0),
        "anisotropic_region_ratio": sdf_summary.get("anisotropic_region_ratio", 0.0),
        "rearward_extension_score": sdf_summary.get("rearward_extension_score", 0.0),
        "front_compression_score": sdf_summary.get("front_compression_score", 0.0),
        "directional_readability_score": sdf_summary.get("directional_readability_score", 0.0),
        "symmetric_volume_penalty": sdf_summary.get("symmetric_volume_penalty", 0.0),
        "hat_pointed_back_present": sdf_summary.get("hat_pointed_back_present", False),
        "front_hat_extension_score": sdf_summary.get("front_hat_extension_score", 0.0),
        "back_hat_extension_score": sdf_summary.get("back_hat_extension_score", 0.0),
        "hat_asymmetry_ratio": sdf_summary.get("hat_asymmetry_ratio", 0.0),
        "surface_flow_enabled": surface_flow_enabled,
        "semantic_transition_count": sdf_summary.get("semantic_transition_count", 0),
        "surface_continuity_score": sdf_summary.get("surface_continuity_score", 0.0),
        "semantic_seam_score": sdf_summary.get("semantic_seam_score", 0.0),
        "oblique_surface_readability": sdf_summary.get("oblique_surface_readability", 0.0),
        "surface_fragmentation_score": sdf_summary.get("surface_fragmentation_score", 0.0),
        "staircase_artifact_score": sdf_summary.get("staircase_artifact_score", 0.0),
        "anatomical_flow_score": sdf_summary.get("anatomical_flow_score", 0.0),
        "rfd_enabled": rfd_enabled,
        "rfd_region_count": sdf_summary.get("rfd_region_count", 0),
        "centerline_quality_score": sdf_summary.get("centerline_quality_score", 0.0),
        "field_continuity_score": sdf_summary.get("field_continuity_score", 0.0),
        "thickness_profile_variance": sdf_summary.get("thickness_profile_variance", 0.0),
        "anisotropy_score": sdf_summary.get("anisotropy_score", 0.0),
        "directional_field_coherence": sdf_summary.get("directional_field_coherence", 0.0),
        "surface_flow_rfd_alignment": sdf_summary.get("surface_flow_rfd_alignment", 0.0),
        "silhouette_constraint_preservation": sdf_summary.get("silhouette_constraint_preservation", 0.0),
        "semantic_remesh_enabled": False,
        "surface_net_vertex_placement": "average",
        "qef_enabled": False,
        "qef_cells_processed": 0,
        "qef_cells_accepted": 0,
        "qef_cells_rejected": 0,
        "qef_acceptance_ratio": 0.0,
        "qef_mean_displacement": 0.0,
        "qef_max_displacement": 0.0,
        "qef_max_displacement_limit": 0.0,
        "qef_fallback_count": 0,
        "qef_condition_warning_count": 0,
        "staircase_artifact_before_qef": 0.0,
        "staircase_artifact_after_qef": 0.0,
        "surface_flow_before_qef": 0.0,
        "surface_flow_after_qef": 0.0,
        "planar_surface_score_before_qef": 0.0,
        "planar_surface_score_after_qef": 0.0,
        "qef_quality_metric_improved": False,
        "semantic_patch_nets_enabled": False,
        "patch_profile": "",
        "patch_count": 0,
        "mean_patch_size": 0.0,
        "small_patch_ratio": 0.0,
        "planar_patch_count": 0,
        "curved_patch_count": 0,
        "silhouette_patch_count": 0,
        "semantic_boundary_patch_count": 0,
        "macro_patches_enabled": False,
        "micro_patch_count": 0,
        "macro_patch_count": 0,
        "macro_patch_reduction_ratio": 0.0,
        "mean_macro_patch_size": 0.0,
        "small_macro_patch_ratio": 0.0,
        "planar_macro_patch_count": 0,
        "curved_macro_patch_count": 0,
        "directional_feature_macro_patch_count": 0,
        "noise_fragments_absorbed": 0,
        "macro_patch_coherence_score": 0.0,
        "triangle_count_before_patch": 0,
        "triangle_count_after_patch": 0,
        "patch_coherence_score": 0.0,
        "triangle_count_before": 0,
        "triangle_count_after": 0,
        "triangle_reduction_ratio": 0.0,
        "coplanar_merge_count": 0,
        "staircase_artifact_before": 0.0,
        "staircase_artifact_after": 0.0,
        "surface_flow_before": 0.0,
        "surface_flow_after": 0.0,
        "silhouette_edge_preservation_score": 0.0,
        "directional_feature_preservation_score": 0.0,
        "planar_surface_score": 0.0,
        "oblique_readability_score": 0.0,
        "lowpoly_coherence_score": 0.0,
        "non_manifold_before_cleanup": 0,
        "non_manifold_after_cleanup": 0,
        "duplicate_faces_removed": 0,
        "duplicate_vertices_merged": 0,
        "sliver_faces_removed": 0,
        "topology_cleanup_applied": False,
        "fail_conditions": fail_conditions,
        "passed": not any(fail_conditions.values()),
    }
